"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Настройки читаются из файла .env (см. .env.example), который не хранится
# в репозитории. Так секреты не попадают в историю git.

# Ключ подписи сессий и токенов. Значения по умолчанию намеренно нет:
# без .env проект должен упасть с понятной ошибкой, а не тихо запуститься
# на общеизвестном запасном ключе.
SECRET_KEY = config('SECRET_KEY')

# По умолчанию False: если переменную забыли задать, срабатывает
# безопасный вариант, а не режим отладки на боевом сервере.
DEBUG = config('DEBUG', default=False, cast=bool)

# Csv() превращает строку «127.0.0.1,localhost» в список из двух элементов.
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catalog',
    'cart',
    'orders',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Параметры подключения лежат в .env: пароль не должен попадать в код.
# Драйвер — psycopg 3, ставится как psycopg[binary].
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='127.0.0.1'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Logging
# https://docs.djangoproject.com/en/6.0/topics/logging/

# ВАЖНО: в логи не пишутся персональные данные (ФИО, адреса, телефоны).
# Только идентификаторы: order_id=42, user_id=7. Лог — это тоже хранилище
# ПДн, но в отличие от БД его легко случайно скопировать или закоммитить.
# Принцип минимизации ПДн (152-ФЗ) распространяется и на него.

LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)  # Django сам каталог не создаёт

LOGGING = {
    'version': 1,
    # Не выключаем встроенные логгеры Django — иначе потеряем его сообщения.
    'disable_existing_loggers': False,

    'formatters': {
        # Для файла: подробно, с датой и местом в коде.
        'verbose': {
            'format': '{asctime} {levelname:8} {name} — {message}',
            'style': '{',
        },
        # Для консоли: коротко, чтобы не мешало при разработке.
        'simple': {
            'format': '{levelname:8} {message}',
            'style': '{',
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            # В разработке видим всё, на боевом сервере — только предупреждения.
            'level': 'DEBUG' if DEBUG else 'WARNING',
        },
        'file': {
            # Ротация: когда файл дорастает до 5 МБ, он переименовывается
            # в django.log.1, и запись начинается заново. Храним 5 таких копий,
            # то есть лог не может занять больше ~30 МБ.
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'level': 'INFO',
            'encoding': 'utf-8',  # без этого кириллица в логе превратится в мусор
        },
    },

    'loggers': {
        # Сообщения самого Django: в файл пишем только проблемы.
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Наши приложения: бизнес-события уровня INFO и выше.
        'catalog': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'cart': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'orders': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
        'users': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
    },
}